# ci-pipeline/ansible/site.yml
---
- name: Apply common configuration on all Linux hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Frontend servers
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Configure Backend servers
  hosts: backend
  become: yes
  roles:
    - backend
