---
- name: Apply common configuration
  hosts: all
  become: yes
  tasks:
    - import_playbook: playbooks/common.yml

- name: Configure frontend servers
  hosts: frontend
  become: yes
  tasks:
    - import_playbook: playbooks/frontend.yml

- name: Configure backend servers
  hosts: backend
  become: yes
  tasks:
    - import_playbook: playbooks/backend.yml
